// Generated by CoffeeScript 1.3.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

$(function() {
  return new Main(800, 600);
});

window.Main = (function() {

  function Main(WIDTH, HEIGHT) {
    this.WIDTH = WIDTH;
    this.HEIGHT = HEIGHT;
    this.gameLoop = __bind(this.gameLoop, this);

    this.ctx;
    this.gameLoopInterval;
    this.buildCanvas();
    this.startGame();
  }

  Main.prototype.startGame = function() {
    return this.gameLoopInterval = setInterval(this.gameLoop, 1);
  };

  Main.prototype.stopGame = function() {
    return clearInterval(this.gameLoopInterval);
  };

  Main.prototype.update = function() {};

  Main.prototype.render = function() {};

  Main.prototype.gameLoop = function() {
    return console.log('loop');
  };

  Main.prototype.buildCanvas = function() {
    var canvas;
    canvas = document.createElement("canvas");
    this.ctx = canvas.getContext("2d");
    canvas.width = this.WIDTH;
    canvas.height = this.HEIGHT;
    return document.body.appendChild(canvas);
  };

  return Main;

})();
